name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest
        
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:password@localhost/realworld_axum_sqlx
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Database
      run: |
        cargo install sqlx-cli --features postgres
        sqlx db setup
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose
    - name: Checkout Realworld Repo
      uses: actions/checkout@v2
      with:
        repository: gothinkster/realworld
        path: realworld
    - name: Run integration tests
      run: |
        cargo run&
        cd ../realworld/api
        ./run-tests.sh
